- block: 
  - name: import repository gpg key
    apt_key:
      url: https://packages.grafana.com/gpg.key

  - name: import repository for stable
    apt_repository:
      repo: deb https://packages.grafana.com/oss/deb stable main
      filename: grafana
      update_cache: yes

  - name: Install grafana
    apt:
      name: grafana
  when: (grafana_version) == "latest"

- name: Install Grafana
  apt:
    deb: "{{grafana_version_meta[grafana_version].Debian}}"
  when: (grafana_version) != "latest"
