# Install Grafana
- include: "{{ansible_os_family}}.yml"

# Configure Grafana

- name: Start grafana
  service:
    name: grafana-server
    state: started
    enabled: yes

# set soft link
- name: set soft link
  shell: |
    ln -sf /usr/share/grafana  /data/wwwroot
    ln -sf /usr/share/grafana/conf /data/config
    ln -sf /var/log/grafana /data/logs

# display version and service state of components
- name: Get Grafana version
  shell: sudo sh -c "grafana-cli -v 1>> /data/logs/install_version.txt"

- name: Check Grafana Service
  shell: systemctl status grafana-server | grep Active*
  register: check_grafana_service
  notify: check_grafana_service
