# Install Grafana
- include: "{{ansible_os_family}}.yml"

# Configure Grafana

- name: Start grafana
  service:
    name: grafana-server
    state: started
    enabled: yes

# set soft link
- name: set soft link
  shell: |
    ln -s /usr/share/grafana  /data/wwwroot/grafana
    ln -s /usr/share/grafana/conf /data/config/grafana
    ln -s /var/log/grafana /data/logs/grafana

# display version and service state of components
- name: Get Grafana version
  shell: grafana-cli -v
  register: check_grafana_version
  notify: check_grafana_version

- name: Check Grafana Service
  shell: systemctl status grafana-server | grep Active*
  register: check_grafana_service
  notify: check_grafana_service
