# 服务器前置任务(ubuntu使用)
- name: Pre_tasks of Grafana
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: False
  pre_tasks:
   - name: Install Python
     raw: sudo apt update && sudo apt-get -y install python


# # 核心任务

- name: Grafana
  hosts: all
  become: yes
  become_method: sudo

  roles:
    - { role: common, tags: "common"}  
    - { role: nginx, tags: "nginx"}     
    - { role: grafana, tags: "grafana"}
    - { role: end, tags: "end"}
                                     